# Generated by Django 5.1.1 on 2024-09-29 17:46

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            product.slug = slugify(product.name)  # Генерация слага на основе имени продукта
            product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_auto_20240929_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, null=True),
        ),
        migrations.RunPython(generate_slugs),  # Генерация слагов для существующих товаров
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),  # Изменяем null=True на обязательное поле
        ),
    ]
